namespace ExceptionMessageSeparation;

/// <summary>
/// Serves as an abstract base class for custom exceptions,
/// providing a mechanism to define exception messages in a type-safe manner.
/// </summary>
/// <typeparam name="TChildException">The specific type of child exception that extends this base class.</typeparam>
/// <typeparam name="TChildExceptionMessage">The message type of the child exception.</typeparam>
/// <param name="inner">An optional inner exception to wrap.</param>
/// <remarks>
/// This class ensures that exceptions can be created with standard messaging logic,
/// while allowing for flexibility and separation of exception message definition 
/// from the exception class definition.
/// </remarks>
public abstract class ExceptionBase<TChildException, TChildExceptionMessage>(Exception? inner = default) : Exception(string.Empty, inner)
    where TChildException : ExceptionBase<TChildException, TChildExceptionMessage>
    where TChildExceptionMessage : struct, IExceptionMessage<TChildException>
{
    /// <summary>
    /// Gets the message that describes the currect exception
    /// </summary>
    /// <returns>
    /// An error message that explains the reason for the exception 
    /// generated by <see cref="IExceptionMessage{TChildException}.For(TChildException)"/> method 
    /// </returns>
    public override string Message => new TChildExceptionMessage().For((TChildException)this);
}